from __future__ import annotations

SETTINGS_BACKUP_CREATED = "SETTINGS_BACKUP_CREATED"
SETTINGS_RESTORED = "SETTINGS_RESTORED"
SETTINGS_MIGRATED = "SETTINGS_MIGRATED"
SETTINGS_RECOVERED = "SETTINGS_RECOVERED"
SETTINGS_ROLLED_BACK = "SETTINGS_ROLLED_BACK"
SETTINGS_CORRUPTED = "SETTINGS_CORRUPTED"
