team:
  enabled: true
  users:
    - id: owner
      name: Markus
      role: admin
  roles:
    admin:
      read: true
      write: true
      configure: true
    editor:
      read: true
      write: true
      configure: false
    viewer:
      read: true
      write: false
      configure: false
